import type { Member } from "@/lib/types";

/**
 * PLACEHOLDER DATA — not real people.
 *
 * Rendered on /recruitment only when Firestore is unconfigured or has no
 * members with `visibleToRecruiters: true` yet, so the page never ships a
 * blank grid during development. Every name here is plainly fictional.
 */
export const SAMPLE_MEMBERS: Member[] = [
  {
    id: "sample-1",
    firstName: "Mai",
    lastName: "Nakamura-Ford",
    email: "mai.sample@ou.edu",
    major: "Computer Science",
    gradYear: 2026,
    classification: "Senior",
    skills: ["Python", "React", "SQL", "AWS", "Git", "Java"],
    bio: "Full-stack developer who has interned twice on developer-tooling teams and leads OU SASE's technical workshops.",
    visibleToRecruiters: true,
    seeking: ["Full-time", "Internship"],
    linkedinUrl: "https://linkedin.com/in/example-mai",
    githubUrl: "https://github.com/example-mai",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "sample-2",
    firstName: "Arjun",
    lastName: "Patel-Cross",
    email: "arjun.sample@ou.edu",
    major: "Electrical Engineering",
    gradYear: 2027,
    classification: "Junior",
    skills: ["MATLAB", "C++", "Circuit Design", "PCB Layout"],
    bio: "Interested in power systems and signal processing; two semesters of undergraduate research on grid resilience.",
    visibleToRecruiters: true,
    seeking: ["Internship", "Co-op"],
    linkedinUrl: "https://linkedin.com/in/example-arjun",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "sample-3",
    firstName: "Lin",
    lastName: "Zhao-Bennett",
    email: "lin.sample@ou.edu",
    major: "Chemical Engineering",
    gradYear: 2025,
    classification: "Senior",
    skills: ["Aspen Plus", "Process Design", "Data Analysis", "R"],
    bio: "Graduating this spring, looking for a process engineering role in energy or materials. Chapter treasurer for two years.",
    visibleToRecruiters: true,
    seeking: ["Full-time"],
    portfolioUrl: "https://example.com/lin-portfolio",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "sample-4",
    firstName: "Devon",
    lastName: "Okafor-Lee",
    email: "devon.sample@ou.edu",
    major: "Computer Engineering",
    gradYear: 2028,
    classification: "Sophomore",
    skills: ["C", "Embedded Systems", "Verilog", "Linux"],
    bio: "Building an embedded robotics project this year and looking for a first internship in firmware or hardware.",
    visibleToRecruiters: true,
    seeking: ["Internship", "Research"],
    githubUrl: "https://github.com/example-devon",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "sample-5",
    firstName: "Priya",
    lastName: "Ramirez-Singh",
    email: "priya.sample@ou.edu",
    major: "Industrial & Systems Engineering",
    gradYear: 2026,
    classification: "Senior",
    skills: ["Six Sigma", "SQL", "Tableau", "Excel", "Python"],
    bio: "Supply chain and operations focus; summer internship in manufacturing analytics, now hunting for a full-time offer.",
    visibleToRecruiters: true,
    seeking: ["Full-time", "Co-op"],
    linkedinUrl: "https://linkedin.com/in/example-priya",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "sample-6",
    firstName: "Kenji",
    lastName: "Alvarez-Wu",
    email: "kenji.sample@ou.edu",
    major: "Computer Science",
    gradYear: 2027,
    classification: "Junior",
    skills: ["TypeScript", "Next.js", "Node.js", "Docker", "PostgreSQL"],
    bio: "Web development and cloud infrastructure. Built the chapter's internal event-check-in tool as a volunteer project.",
    visibleToRecruiters: true,
    seeking: ["Internship"],
    githubUrl: "https://github.com/example-kenji",
    linkedinUrl: "https://linkedin.com/in/example-kenji",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
];
